package com.wanderersoftherift.wotr.gui.menu.character;

import com.wanderersoftherift.wotr.init.WotrMenuTypes;
import net.minecraft.network.chat.Component;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.ContainerLevelAccess;
import net.minecraft.world.inventory.MenuType;
import org.jetbrains.annotations.Nullable;

import java.util.List;

public abstract class BaseCharacterMenu extends AbstractContainerMenu {
    public static final List<CharacterMenuItem> ITEMS = List.of(
            new CharacterMenuItem(Component.literal("Guilds"), WotrMenuTypes.GUILDS_MENU.get(),
                    (id, inventory, player) -> new GuildMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos()))),
            new CharacterMenuItem(Component.literal("Wallet"), WotrMenuTypes.WALLET_MENU.get(),
                    (id, inventory, player) -> new WalletMenu(id, inventory,
                            ContainerLevelAccess.create(player.level(), player.getOnPos())))
    );

    protected BaseCharacterMenu(@Nullable MenuType<?> menuType, int containerId) {
        super(menuType, containerId);
    }
}
